#!/bin/bash
dconf write /org/gnome/desktop/background/picture-uri "'file:///usr/share/backgrounds/Ubuntu_80s_glitch_by_Abubakar_NK.jpg'"
dconf write /org/gnome/desktop/interface/clock-show-weekday "true"
dconf write /org/gnome/desktop/interface/cursor-theme "'Breeze_Snow'"
dconf write /org/gnome/desktop/interface/gtk-theme "'Yaru-dark'"
dconf write /org/gnome/desktop/interface/icon-theme "'Yaru'"
dconf write /org/gnome/desktop/interface/show-battery-percentage "true"
dconf write /org/gnome/desktop/peripherals/touchpad/tap-to-click "true"
dconf write /org/gnome/desktop/screensaver/picture-uri "'file:///usr/share/backgrounds/Ubuntu_80s_glitch_by_Abubakar_NK.jpg'"
dconf write /org/gnome/desktop/wm/preferences/button-layout "':minimize,maximize,close'"
dconf write /org/gnome/gedit/preferences/editor/background-pattern "'grid'"
dconf write /org/gnome/gedit/preferences/editor/bracket-matching "true"
dconf write /org/gnome/gedit/preferences/editor/display-line-numbers "true"
dconf write /org/gnome/gedit/preferences/editor/display-right-margin "true"
dconf write /org/gnome/gedit/preferences/editor/highlight-current-line "true"
dconf write /org/gnome/gedit/preferences/editor/scheme "'cobalt'"
dconf write /org/gnome/gedit/preferences/editor/wrap-mode "'word'"
dconf write /org/gnome/mutter/center-new-windows "true"
dconf write /org/gnome/nautilus/window-state/maximized "false"
dconf write /org/gnome/shell/disable-user-extensions "false"
dconf write /org/gnome/shell/extensions/dash-to-dock/click-action "'minimize'"
dconf write /org/gnome/shell/extensions/dash-to-dock/dock-fixed "true"
dconf write /org/gnome/shell/extensions/dash-to-dock/show-trash "false"
dconf write /org/gnome/shell/extensions/desktop-icons/show-home "false"
dconf write /org/gnome/shell/extensions/desktop-icons/show-mount "true"
dconf write /org/gnome/shell/extensions/desktop-icons/show-trash "true"
dconf write /org/gnome/shell/extensions/user-theme/name "'Yaru-dark'"
dconf write /org/gnome/terminal/legacy/menu-accelerator-enabled "false"
dconf write /org/gnome/terminal/legacy/mnemonics-enabled "false"
dconf write /org/gnome/Disks/image-dir-uri "'~/Pobrane'"
dconf write /org/gnome/baobab/preferences/excluded-uris "['file:///sys', 'file:///dev', 'file:///proc']"
dconf write /org/gnome/calculator/refresh-interval "86400"
dconf write /org/gnome/calculator/source-currency "'PLN'"
dconf write /org/gnome/calculator/target-currency "'PLN'"
dconf write /org/gnome/calendar/window-maximized "true"
dconf write /org/gnome/calendar/active-view "'year'"

